### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [ronmackley/zsh-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots in the readme so that users can see what they look like without having to install them.

Also, please add a license file, some people won't use any code that doesn't have an open source license. If you don't have one in mind, https://choosealicense.com is a good resource to help you select an appropriate one.

Please also consider renaming it to something descriptive, or even just name it after your github username.

Thanks!

**Comment by ronmackley** [comment]
Hello Joe! 

That was fast! I decided spend some time to try out oh-my-zsh, make a theme, and try out this GitHub thing I keep hearing about. Then the next day I get a comment form you. Thanks for your interest.

I made a new repository that is basically this, with:
- A more meaningful name.
- A screen shot.
- A license.

You can find it here: [frank-theme](https://github.com/ronmackley/frank-theme)

You are welcome to add it to your zsh-plugins list if you wish. 

Regards,

Ron

**Comment by ronmackley** [comment]
Closing. Above has been addressed in successor repo.
